package io.casehub.platform.callback.generator;

import org.jboss.jandex.AnnotationInstance;
import org.jboss.jandex.AnnotationTarget;
import org.jboss.jandex.AnnotationValue;
import org.jboss.jandex.ClassInfo;
import org.jboss.jandex.CompositeIndex;
import org.jboss.jandex.DotName;
import org.jboss.jandex.IndexReader;
import org.jboss.jandex.IndexView;
import org.jboss.jandex.MethodInfo;
import org.jboss.jandex.Type;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.net.URL;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@SupportedAnnotationTypes("*")
@SupportedSourceVersion(SourceVersion.RELEASE_21)
public class CallbackDecoratorProcessor extends AbstractProcessor {

    private static final DotName CALLBACK_ELIGIBLE =
            DotName.createSimple("io.casehub.platform.api.mcp.CallbackEligible");

    private static final String GENERATED_PACKAGE = "io.casehub.platform.callback.generated";

    private boolean processed = false;

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (processed || roundEnv.processingOver()) {
            return false;
        }
        processed = true;

        IndexView index = loadCombinedIndex();
        if (index == null) {
            return false;
        }

        List<GeneratedSource> sources = generateFromIndex(index);
        for (GeneratedSource source : sources) {
            writeSourceFile(source);
        }

        return false;
    }

    List<GeneratedSource> generateFromIndex(IndexView index) {
        List<GeneratedSource> results = new ArrayList<>();

        for (AnnotationInstance ann : index.getAnnotations(CALLBACK_ELIGIBLE)) {
            if (ann.target().kind() != AnnotationTarget.Kind.CLASS) continue;
            ClassInfo classInfo = ann.target().asClass();
            if (!java.lang.reflect.Modifier.isInterface(classInfo.flags())) continue;

            AnnotationValue nameVal = ann.value("name");
            String spiName = (nameVal != null && !nameVal.asString().isEmpty())
                    ? nameVal.asString()
                    : toKebabCase(classInfo.simpleName());

            AnnotationValue fanOutVal = ann.value("fanOut");
            boolean fanOut = fanOutVal == null || fanOutVal.asBoolean();

            String decoratorName = "Callback" + classInfo.simpleName() + "Decorator";
            String fqcn = GENERATED_PACKAGE + "." + decoratorName;
            String source = generateDecoratorSource(classInfo, spiName, fanOut, decoratorName);

            results.add(new GeneratedSource(fqcn, source));
        }

        return results;
    }

    private String generateDecoratorSource(ClassInfo spiClass, String spiName,
                                           boolean fanOut, String decoratorName) {
        StringBuilder sb = new StringBuilder();
        String spiSimpleName = spiClass.simpleName();
        String spiFullName = spiClass.name().toString();

        sb.append("package ").append(GENERATED_PACKAGE).append(";\n\n");

        sb.append("import jakarta.decorator.Decorator;\n");
        sb.append("import jakarta.decorator.Delegate;\n");
        sb.append("import jakarta.annotation.Priority;\n");
        sb.append("import jakarta.inject.Inject;\n");
        sb.append("import io.casehub.platform.api.callback.CallbackRegistration;\n");
        sb.append("import io.casehub.platform.api.callback.CallbackRegistry;\n");
        sb.append("import io.casehub.platform.callback.CallbackInvoker;\n");
        sb.append("import io.casehub.platform.api.identity.CurrentPrincipal;\n");
        sb.append("import java.util.List;\n");
        sb.append("import ").append(spiFullName).append(";\n");

        Set<String> paramImports = collectParameterImports(spiClass);
        for (String imp : paramImports) {
            sb.append("import ").append(imp).append(";\n");
        }

        sb.append("\n");
        sb.append("// GENERATED by CallbackDecoratorProcessor — do not edit\n");
        sb.append("@Decorator\n");
        sb.append("@Priority(jakarta.interceptor.Interceptor.Priority.APPLICATION + 100)\n");
        sb.append("public class ").append(decoratorName);
        sb.append(" implements ").append(spiSimpleName).append(" {\n\n");

        sb.append("    @Inject @Delegate ").append(spiSimpleName).append(" delegate;\n");
        sb.append("    @Inject CallbackRegistry callbackRegistry;\n");
        sb.append("    @Inject CallbackInvoker invoker;\n");
        sb.append("    @Inject CurrentPrincipal currentPrincipal;\n\n");

        for (MethodInfo method : spiClass.methods()) {
            if (method.isSynthetic()) continue;
            generateMethod(sb, method, spiName, fanOut);
        }

        sb.append("}\n");
        return sb.toString();
    }

    private void generateMethod(StringBuilder sb, MethodInfo method,
                                String spiName, boolean fanOut) {
        String returnType = typeToJava(method.returnType());
        boolean isVoid = method.returnType().kind() == Type.Kind.VOID;

        StringBuilder params = new StringBuilder();
        StringBuilder args = new StringBuilder();
        StringBuilder argsArray = new StringBuilder();
        argsArray.append("new Object[]{");
        for (int i = 0; i < method.parameterTypes().size(); i++) {
            if (i > 0) {
                params.append(", ");
                args.append(", ");
                argsArray.append(", ");
            }
            String paramType = typeToJava(method.parameterTypes().get(i));
            String paramName = method.parameterName(i) != null ? method.parameterName(i) : "arg" + i;
            params.append(paramType).append(" ").append(paramName);
            args.append(paramName);
            argsArray.append(paramName);
        }
        argsArray.append("}");

        sb.append("    @Override\n");
        sb.append("    public ").append(returnType).append(" ").append(method.name());
        sb.append("(").append(params).append(") {\n");

        sb.append("        String tenancyId = currentPrincipal.tenancyId();\n");
        sb.append("        List<CallbackRegistration> registrations = ");
        sb.append("callbackRegistry.findBySpi(\"").append(spiName).append("\", tenancyId);\n\n");

        sb.append("        if (registrations.isEmpty()) {\n");
        if (isVoid) {
            sb.append("            delegate.").append(method.name()).append("(").append(args).append(");\n");
            sb.append("            return;\n");
        } else {
            sb.append("            return delegate.").append(method.name()).append("(").append(args).append(");\n");
        }
        sb.append("        }\n\n");

        if (fanOut) {
            if (isVoid) {
                sb.append("        for (CallbackRegistration reg : registrations) {\n");
                sb.append("            invoker.invoke(reg, \"").append(method.name()).append("\", ");
                sb.append(argsArray).append(", void.class);\n");
                sb.append("        }\n");
            } else {
                sb.append("        for (CallbackRegistration reg : registrations) {\n");
                sb.append("            ").append(returnType).append(" result = ");
                sb.append("invoker.invoke(reg, \"").append(method.name()).append("\", ");
                sb.append(argsArray).append(", ").append(returnType).append(".class);\n");
                sb.append("            if (result != null) return result;\n");
                sb.append("        }\n");
                sb.append("        return delegate.").append(method.name()).append("(").append(args).append(");\n");
            }
        } else {
            sb.append("        CallbackRegistration reg = registrations.get(0);\n");
            if (isVoid) {
                sb.append("        invoker.invoke(reg, \"").append(method.name()).append("\", ");
                sb.append(argsArray).append(", void.class);\n");
            } else {
                sb.append("        return invoker.invoke(reg, \"").append(method.name()).append("\", ");
                sb.append(argsArray).append(", ").append(returnType).append(".class);\n");
            }
        }

        sb.append("    }\n\n");
    }

    private Set<String> collectParameterImports(ClassInfo spiClass) {
        Set<String> imports = new HashSet<>();
        for (MethodInfo method : spiClass.methods()) {
            if (method.isSynthetic()) continue;
            for (Type paramType : method.parameterTypes()) {
                addTypeImport(imports, paramType);
            }
            if (method.returnType().kind() != Type.Kind.VOID) {
                addTypeImport(imports, method.returnType());
            }
        }
        return imports;
    }

    private void addTypeImport(Set<String> imports, Type type) {
        switch (type.kind()) {
            case CLASS -> {
                String name = type.name().toString();
                if (!name.startsWith("java.lang.") || name.indexOf('.', 10) > 0) {
                    imports.add(name);
                }
            }
            case PARAMETERIZED_TYPE -> {
                imports.add(type.asParameterizedType().name().toString());
                for (Type arg : type.asParameterizedType().arguments()) {
                    addTypeImport(imports, arg);
                }
            }
            case ARRAY -> addTypeImport(imports, type.asArrayType().constituent());
            default -> {}
        }
    }

    static String toKebabCase(String camelCase) {
        if (camelCase == null || camelCase.isEmpty()) return camelCase;

        StringBuilder result = new StringBuilder();
        for (int i = 0; i < camelCase.length(); i++) {
            char c = camelCase.charAt(i);
            if (Character.isUpperCase(c)) {
                if (i > 0) {
                    boolean prevUpper = Character.isUpperCase(camelCase.charAt(i - 1));
                    boolean nextLower = (i + 1 < camelCase.length())
                            && Character.isLowerCase(camelCase.charAt(i + 1));
                    if (!prevUpper || nextLower) {
                        result.append('-');
                    }
                }
                result.append(Character.toLowerCase(c));
            } else {
                result.append(c);
            }
        }
        return result.toString();
    }

    private String typeToJava(Type type) {
        return switch (type.kind()) {
            case VOID -> "void";
            case PRIMITIVE -> type.asPrimitiveType().primitive().name().toLowerCase();
            case CLASS -> type.asClassType().name().local();
            case PARAMETERIZED_TYPE -> {
                StringBuilder sb = new StringBuilder(type.asParameterizedType().name().local());
                sb.append("<");
                List<Type> args = type.asParameterizedType().arguments();
                for (int i = 0; i < args.size(); i++) {
                    if (i > 0) sb.append(", ");
                    sb.append(typeToJava(args.get(i)));
                }
                sb.append(">");
                yield sb.toString();
            }
            case ARRAY -> typeToJava(type.asArrayType().constituent()) + "[]";
            default -> type.name().toString();
        };
    }

    private IndexView loadCombinedIndex() {
        List<IndexView> indexes = new ArrayList<>();
        try {
            ClassLoader cl = getClass().getClassLoader();
            Enumeration<URL> resources = cl.getResources("META-INF/jandex.idx");
            while (resources.hasMoreElements()) {
                URL url = resources.nextElement();
                try (InputStream is = url.openStream()) {
                    indexes.add(new IndexReader(is).read());
                }
            }
        } catch (IOException e) {
            if (processingEnv != null) {
                processingEnv.getMessager().printMessage(Diagnostic.Kind.WARNING,
                        "Callback generator: failed to read Jandex indexes: " + e.getMessage());
            }
            return null;
        }

        if (indexes.isEmpty()) {
            return null;
        }

        if (processingEnv != null) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                    "Callback generator: loaded " + indexes.size() + " Jandex index(es)");
        }
        return CompositeIndex.create(indexes);
    }

    private void writeSourceFile(GeneratedSource source) {
        try {
            JavaFileObject file = processingEnv.getFiler().createSourceFile(source.className());
            try (PrintWriter out = new PrintWriter(file.openWriter())) {
                out.print(source.sourceCode());
            }

            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                    "Callback generator: generated " + source.className());

        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "Callback generator: failed to write " + source.className() + ": " + e.getMessage());
        }
    }

    record GeneratedSource(String className, String sourceCode) {}
}
